### ISSUE TITLE
Android: Cannot use RNUportHDSigner.createSeed('prompt') without finger print hardware

### ISSUE THREAD

**Issue by DPPaolo** [uport-project/react-native-uport-signer#23]
Hi,
in these days I'm using your library on android and ios but I encountered in various problem only with specific Android devices.
For security reasons, I need security level "prompt", all work fine but the android devices without fingerprint hardware.

I'm using RNUportSigner.hasFingerprintHardware() to check this if the response is true, the creation of the seed works, but when I try to use RNUportHDSigner.showSeed(), after the confirmation of the keyguards the seed doesn't appear, the function doesn't work. 

Otherwise, if the response is false the app crash in the RNUportHDSigner.createSeed('prompt') with the error:
`Error: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use`

The library documentation says "'prompt' - seeds are encrypted and need a fingerprint or keyguard unlocking." but keyguard doesn't appear or don't work in both cases.
Same problems with security level 'singleprompt'

Tested on:
- react-native 0.59.8
- react-native-uport-signer 1.3.4
- Huawei P8 Light 2015, Samsung S10,  Android Emulator, iPhone XS

Thanks

**Comment by mirceanis** [comment]
@Hikoaki the library is supposed to throw an error if you try to use the `prompt` or `singleprompt` without having set a pin/pattern/password/fingerprint on the device.
If the device has fingerprint hardware but no fingerprints are enrolled it should degrade gracefully to pin/pattern/password protection.

To be able to use the `prompt` or `singleprompt` protection levels, the device needs to have been setup with at least one of pin/password/pattern/fingerprint lockscreen.

On android you may use `RNUportSigner.hasSecureKeyguard()` to check if any of the above are setup. In case they are not, you may also use `RNUportSigner.launchSecuritySettings()` to direct the user to setup a lockscreen.

I hope this helps

**Comment by DPPaolo** [comment]
Thanks for the answer, it helped a bit but not at all. 

My problem persists with this specific configuration:

- `RNUportSigner.hasSecureKeyguard()` return true (i've a pattern, but it's the same of PIN or password)
- `RNUportSigner.hasFingerprintHardware()` return false (the device doesn't have fingerprint hardware)
- `RNUportSigner.hasSetupFingerprints()` return false

On Android `RNUportHDSigner.createSeed('prompt')` throws the error `At least one fingerprint must be enrolled to create keys requiring user authentication for every use`, as I said on the comment above, instead of Ios where the library uses a different secure keyguard if there isn't any fingerprint hardware on the device.

I hope it's clear, thanks.

**Comment by DPPaolo** [comment]
Some news about this problem? I can't use your library without a fingerprint hardware.

**Comment by mirceanis** [comment]
So far, I was unable to reproduce this behavior.
Can you make sure you are using the latest version of the library (1.4.4) by checking `package.json` and then removing `node_modules` and reinstalling them?

It is possible this bug manifests in older versions of the library.

**Comment by DPPaolo** [comment]
Tested with version 1.4.4, same problem : `Error: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use`

**Comment by mirceanis** [comment]
> Tested with version 1.4.4, same problem : `Error: java.lang.IllegalStateException: At least one fingerprint must be enrolled to create keys requiring user authentication for every use`

@Hikoaki 
The branch [support/167135603-demo-rn59](https://github.com/uport-project/react-native-signer-demo/pull/9) of the sample app is using react-native 0.59.8 and react-native-uport-signer 1.4.4 and does not seem to exhibit the behavior you mention.

Can you confirm this on your devices?

**Comment by DPPaolo** [comment]
Tested with my device (Huawei P8 Lite 2015), the problem is still here. I clicked on HD Signer but the error happens also with the basic signer:
![photo_2019-07-13_21-49-43](https://user-images.githubusercontent.com/11560231/61181127-ff5e1c00-a621-11e9-9323-39729db17d8c.jpg)

**Comment by mirceanis** [comment]
@Hikoaki I've finally tracked down the root cause of this issue.
Apparently the issue is deep within the `AndroidKeyStore` APIs that are being used to protect the keys/seeds.

Essentially, when creating a wrapping key to protect the seed, there is a parameter that specifies what the authentication window should be. Using `-1` means it should require authentication every time. According to the docs, that should have no effect for devices without fingerprint hardware. BUT it seems to be relevant on some devices, causing that exception.
The fix is to use a `0` second authentication window.

I'll be publishing a new version of [uport-android-signer](https://github.com/uport-project/uport-android-signer) with that fix soon and bumping the version used here.
Stay tuned for v1.4.5 which should include that fix.
