### ISSUE TITLE
HDSigner delete seed

### ISSUE THREAD

**Issue by simonas-notcat** [uport-project/react-native-uport-signer#26]
Maybe this is not a problem, just noticed discrepancy in param names. It is not clear what to pass to `deleteSeed` from RN

`deleteSeed:(NSString *)rootEthereumAddress`
https://github.com/uport-project/react-native-uport-signer/blob/develop/ios/Pods/UPTEthereumSigner/UPTEthereumSigner/Classes/UPTHDSigner.m#L77

`deleteSeed:(NSString *)phrase`
https://github.com/uport-project/react-native-uport-signer/blob/develop/ios/RNUportHDSigner.m#L128

**Comment by mirceanis** [comment]
Nice find!
The parameter that should be passed is the `rootAddress` that was generated when the seed was created or imported.

**Comment by aldigjo** [comment]
this is fixed in v1.5.0
