### ISSUE TITLE
Android package name

### ISSUE THREAD

**Issue by iwashi1t** [uport-project/react-native-uport-signer#33]
The Android package name `com.reactlibrary` is too general, so can you change it to something else? (e.g. `me.uport`)

Duplicate error has occurred when used with a library with the same package name `com.reactlibrary`.

**Comment by mirceanis** [comment]
You are probably right, and the package name could be changed.
We'll add this to the backlog but if you are in a hurry, a PR to fix this would be very welcome.

Thank you for reporting this.
