### ISSUE TITLE
this package itself specifies a `main` module field that could not be resolved

### ISSUE THREAD

**Issue by iwashi1t** [uport-project/react-native-uport-signer#36]
The following error has occurred after executing `react-native run-android`.

```
error: bundling failed: Error: While trying to resolve module `react-native-uport-signer` from file `***.js`, the package `/***/node_modules/react-native-uport-signer/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/***/node_modules/react-native-uport-signer/lib/index.js`. Indeed, none of these files exist:

  * `/***/node_modules/react-native-uport-signer/lib/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/***/node_modules/react-native-uport-signer/lib/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
```

[package.json (L5)](https://github.com/uport-project/react-native-uport-signer/blob/develop/package.json#L5) says `"main": "lib/index.js"`, but `lib` folder doesn't seem to exist.

It seems that it has been changed from `index.js` to `lib/index.ts` in [commit 8a1d885](
https://github.com/uport-project/react-native-uport-signer/commit/8a1d885bd2a864be17991dc3a15becfb7c240d38#diff-b9cfc7f2cdf78a7f4b91a753d10865a2), is this correct?

### Environment

* react-native: 0.59.9
* react-native-uport-signer: 1.5.1

**Comment by mirceanis** [comment]
Thanks for reporting.
Are you facing the same issue in v1.5.0?

**Comment by iwashi1t** [comment]
Thank you for your prompt reply.

The same happens with v1.5.0. On the other hand, it works well with v1.4.5.

**Comment by mirceanis** [comment]
It looks like an issue with our build setup, most likely coming from the recent migration to TS.

**Comment by mirceanis** [comment]
@iwashi1t please try v1.5.2 it should be fixed now

**Comment by iwashi1t** [comment]
@mirceanis it is perfect! Thank you so much.
