### ISSUE TITLE
[iOS] Is autolink working correctly?

### ISSUE THREAD

**Issue by iwashi1t** [uport-project/react-native-uport-signer#42]
When I run after following the steps below, I get the `Framework not found EthCore` error.

```
react-native init sample
cd sample
npm install react-native-uport-signer
cd ios
(set platform :ios, '11.0')
pod install
open sample.xcworkspace
```

Is autolink now working correctly? If yes, can you add the installation procedure in the Readme when using autolink?

Thank you.

### Versions

- react-native: 0.61.2
- react-native-uport-signer: 1.6.0

**Comment by aldigjo** [comment]
@iwashi1t @loredanacirstea When you are running pod install, what version of `ethCore` and `UPTEthereumSigner` do you see being installed?

**Comment by loredanacirstea** [comment]
@aldigjo,
```
Installing EthCore (1.0.9)
Installing RNUportSigner (1.6.0)
Installing UPTEthereumSigner (1.1.3)
```

**Comment by aldigjo** [comment]
@loredanacirstea Looks like it's not pulling the latest version of UPTEthereumSigner. try running `pod cache clean 'UPTEthereumSigner' --all` and then `pod install` again, see if it pulls version 1.1.5 of `UPTEthereumSigner`

**Comment by loredanacirstea** [comment]
Still pulls `1.1.3`, even after cleaning the pod cache.

**Comment by aldigjo** [comment]
@loredanacirstea ok so im assuming now that in the podfile.lock it shows version `1.1.3` as well, try removing the lock file.

**Comment by loredanacirstea** [comment]
By the way, this was a fresh project. I did `pod cache clean --all` and then removed podfile.lock from my project and reinstalling pods -> same `1.1.3` version.

Indeed `pod update UPTEthereumSigner` pulls `1.1.5` and there is no build error anymore (signer works).

**Comment by iwashi1t** [comment]
After `pod update UPTEthereumSigner`, it works just as well in my environment.

Thank you so much.

**Comment by mirceanis** [comment]
reopening this to make sure things work out of the box, without requiring `pod update`
